GET http://localhost:3001/api/persons
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Lionel Messi",
  "number": 12312312,
}
###
DELETE http://localhost:3001/api/persons/1
